<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="https://monetica.online/galerija.php"
           xmlns:gal="https://monetica.online/galerija"
           xmlns:rad="https://monetica.online/radionice">

    <xs:import namespace="https://monetica.online/radionice" schemaLocation="radionice.xsd"/>

    <xs:element name="galerija">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="gal:djelo"/>
                    <xs:element ref="rad:radionica"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="djelo">
        <xs:complexType>
            <xs:all>
                <xs:element name="naslov">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:pattern value=".*\S.*"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="autor">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:pattern value=".*\S.*"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="tehnika" type="xs:string" minOccurs="0"/>
                <xs:element name="godina">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="1800"/>
                            <xs:maxInclusive value="2100"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="dimenzije" type="xs:string"/>
                <xs:element name="kategorija">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Slikarstvo"/>
                            <xs:enumeration value="Fotografija"/>
                            <xs:enumeration value="Crtež"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="slika" type="xs:string"/>
                <xs:element name="opis" type="xs:string"/>
            </xs:all>
            <xs:attribute name="id" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger"/>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

</xs:schema>
