<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="http://monetica.hr/radionice"
           xmlns:rad="http://monetica.hr/radionice">

    <xs:element name="radionica">
        <xs:complexType>
            <xs:all>
                <xs:element name="naslov">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:pattern value=".*\S.*"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
<xs:element name="opis" type="xs:string"/>
                <xs:element name="slika" type="xs:string"/>
            </xs:all>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>
